site_name: EJS
nav:
  - Home: "index.md"
  - Getting Started: "Getting Started/getStarted.md"
  - Features: "Features/Features.md"
  - Tags: "Tags/tags.md"
  - Express: "Express/express.md"
  - Troubleshooting: "troubleshooting/troubleshooting.md"
  - glossary: "glossary/glossary.md"
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
theme:
  name: material
  icon:
    logo: material/library 
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/keeles

copyright: |
  &copy; 2024 <a href="https://github.com/kurumicake"  target="_blank" rel="noopener">Christy Wan</a><a href="https://github.com/alesstongwei"  target="_blank" rel="noopener">Aless Wei</a><a href="https://github.com/keeles"  target="_blank" rel="noopener">Kyle Eeles</a>
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
