site_name: EJS
nav:
  - Home: "index.md"
  - Getting Started: "Getting Started/getStartedA.md"
  - Features: "Features/Features-c.md"
  - Express: "Express/expressK.md"
  - Usage: "Usage/usageK.md"
  - Troubleshooting: "troubleshooting/troubleshooting.md"
  - glossary: "glossary/glossary.md"

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/keeles

copyright: |
  &copy; 2024 <a href="https://github.com/kurumicake"  target="_blank" rel="noopener">Christy Wan</a><a href="https://github.com/alesstongwei"  target="_blank" rel="noopener">Aless Wei</a><a href="https://github.com/keeles"  target="_blank" rel="noopener">Kyle Eeles</a>
